//
//  SourceEditorAutoPropertyCommand.m
//  ZBSnippet
//
//  Created by xzb on 2019/5/7.
//  Copyright © 2019 xzb. All rights reserved.
//

#import "SourceEditorAutoPropertyCommand.h"

@implementation SourceEditorAutoPropertyCommand

/// 特殊符号
- (NSString *)specialSymbolsAction
{
    //数学符号
    NSString *matSym = @" ﹢﹣×÷±/=≌∽≦≧≒﹤﹥≈≡≠=≤≥<>≮≯∷∶∫∮∝∞∧∨∑∏∪∩∈∵∴⊥∥∠⌒⊙√∟⊿㏒㏑%‰⅟½⅓⅕⅙⅛⅔⅖⅚⅜¾⅗⅝⅞⅘≂≃≄≅≆≇≈≉≊≋≌≍≎≏≐≑≒≓≔≕≖≗≘≙≚≛≜≝≞≟≠≡≢≣≤≥≦≧≨≩⊰⊱⋛⋚∫∬∭∮∯∰∱∲∳%℅‰‱øØπ";
    //标点符号
    NSString *punSym = @"。，、＇：∶；?‘’“”〝〞ˆˇ﹕︰﹔﹖﹑·¨….¸;！´？！～—ˉ｜‖＂〃｀@﹫¡¿﹏﹋﹌︴々﹟#﹩$﹠&﹪%*﹡﹢﹦﹤‐￣¯―﹨ˆ˜﹍﹎+=<＿_-ˇ~﹉﹊（）〈〉‹›﹛﹜『』〖〗［］《》〔〕{}「」【】︵︷︿︹︽_﹁﹃︻︶︸﹀︺︾ˉ﹂﹄︼❝❞!():,'[]｛｝^・.·．•＃＾＊＋＝＼＜＞＆§⋯`－–／—|\"\\";
    //单位符号＊·
    NSString *unitSym = @"°′″＄￥〒￠￡％＠℃℉﹩﹪‰﹫㎡㏕㎜㎝㎞㏎m³㎎㎏㏄º○¤%$º¹²³";
    //货币符号
    NSString *curSym = @"₽€£Ұ₴$₰¢₤¥₳₲₪₵元₣₱฿¤₡₮₭₩ރ円₢₥₫₦zł﷼₠₧₯₨Kčर₹ƒ₸￠";
    //制表符
    NSString *tabSym = @"─ ━│┃╌╍╎╏┄ ┅┆┇┈ ┉┊┋┌┍┎┏┐┑┒┓└ ┕┖┗ ┘┙┚┛├┝┞┟┠┡┢┣ ┤┥┦┧┨┩┪┫┬ ┭ ┮ ┯ ┰ ┱ ┲ ┳ ┴ ┵ ┶ ┷ ┸ ┹ ┺ ┻┼ ┽ ┾ ┿ ╀ ╁ ╂ ╃ ╄ ╅ ╆ ╇ ╈ ╉ ╊ ╋ ╪ ╫ ╬═║╒╓╔ ╕╖╗╘╙╚ ╛╜╝╞╟╠ ╡╢╣╤ ╥ ╦ ╧ ╨ ╩ ╳╔ ╗╝╚ ╬ ═ ╓ ╩ ┠ ┨┯ ┷┏ ┓┗ ┛┳ ⊥ ﹃ ﹄┌ ╮ ╭ ╯╰";
    return [NSString stringWithFormat:@"%@%@%@%@%@", matSym, punSym, unitSym, curSym, tabSym];
}

- (void)performCommandWithInvocation:(XCSourceEditorCommandInvocation *)invocation completionHandler:(void (^)(NSError *_Nullable nilOrError))completionHandler
{
    if (!invocation) {
        completionHandler(nil);
        return;
    }
    self.invocation = invocation;
    //1. 判断选中字符串非空
    XCSourceTextRange *lastRange = [invocation.buffer.selections lastObject];
    
    NSString *selctedLineStr = [invocation.buffer.lines objectAtIndex:lastRange.start.line];
    NSRange selctedRange = NSMakeRange(lastRange.start.column, lastRange.end.column - lastRange.start.column);
    if (selctedRange.location + selctedRange.length > selctedLineStr.length) {
        NSLog(@"⚠️异常,需要选中文字超出行内容");
        completionHandler(nil);
        return;
    }
    NSString *selctedContent = [selctedLineStr substringWithRange:selctedRange];
    NSCharacterSet *set = [NSCharacterSet characterSetWithCharactersInString:[self specialSymbolsAction]];
    selctedContent = [[selctedContent componentsSeparatedByCharactersInSet:set] componentsJoinedByString:@""];
    
    NSString *propertyContent = [self getImplementationContentWithSelcted:selctedContent];
    
    //2. 确定.h还是.m文件
    //    BOOL interfaceFile = [self isInterfaceFile];
    
    //3. 替换内容
    
    NSInteger selctedLineIdx = [self.invocation.buffer.selections.firstObject start].line;
    [invocation.buffer.lines replaceObjectAtIndex:selctedLineIdx withObject:propertyContent];
    
    //4 .m文件 判断有没有extension
    
    //5. 添加extension,在当前选中行之上,找到@implementation 然后添加extension
    
    //6. 判断选中的字符串,过滤特殊字符串
    
    //7.添加property
    
    //8.添加lazy
    
    //9.添加到view上
    //如果是controller的话,
    //如果是cell的话,添加到contentView上
    //10. 设置layout
    
    completionHandler(nil);
}

- (BOOL)isInterfaceFile
{
    for (NSString *line in self.invocation.buffer.lines) {
        if ([line hasPrefix:@"@implementation"]) {
            return NO;
        }
    }
    return YES;
}

- (NSString *)getImplementationContentWithSelcted:(NSString *)selectedContent
{
    for (NSDictionary *info in [self datas]) {
        NSString *key = info[@"key"];
        if ([[selectedContent lowercaseString] containsString:[key lowercaseString]]) {
            NSString *type = info[@"type"];
            NSString *ui = info[@"ui"];
            return [NSString stringWithFormat:@"@property (nonatomic, %@) %@ *%@;", type, ui, selectedContent];
        }
    }
    return @"@property (nonatomic, <# type #>) <# class #>  <# pName #>";
}

- (NSArray <NSDictionary *> *)datas
{
    return @[@{
                 @"key": @"Label",
                 @"type": @"strong",
                 @"ui": @"UILabel"
                 },
             @{
                 @"key": @"Btn",
                 @"type": @"strong",
                 @"ui": @"UIButton"
                 }, @{
                 @"key": @"Button",
                 @"type": @"strong",
                 @"ui": @"UIButton"
                 },
             @{
                 @"key": @"ImageView",
                 @"type": @"strong",
                 @"ui": @"UIImageView"
                 }, @{
                 @"key": @"ImgV",
                 @"type": @"strong",
                 @"ui": @"UIImageView"
                 }, @{
                 @"key": @"View",
                 @"type": @"strong",
                 @"ui": @"UIView"
                 }, @{
                 @"key": @"id",
                 @"type": @"weak",
                 @"ui": @"id"
                 }, @{
                 @"key": @"ImageView",
                 @"type": @"strong",
                 @"ui": @"UIImageView"
                 }, @{
                 @"key": @"Font",
                 @"type": @"strong",
                 @"ui": @"UIFont"
                 }, @{
                 @"key": @"Color",
                 @"type": @"strong",
                 @"ui": @"UIColor"
                 }, @{
                 @"key": @"Array",
                 @"type": @"strong",
                 @"ui": @"NSArray"
                 }, @{
                 @"key": @"Arr",
                 @"type": @"strong",
                 @"ui": @"NSArray"
                 }, @{
                 @"key": @"ImageView",
                 @"type": @"strong",
                 @"ui": @"UIImageView"
                 }, @{
                 @"key": @"Str",
                 @"type": @"copy",
                 @"ui": @"NSString"
                 }, @{
                 @"key": @"height",
                 @"type": @"assign",
                 @"ui": @"CGFloat"
                 }, @{
                 @"key": @"Height",
                 @"type": @"assign",
                 @"ui": @"CGFloat"
                 }, @{
                 @"key": @"Width",
                 @"type": @"assign",
                 @"ui": @"CGFloat"
                 }, @{
                 @"key": @"width",
                 @"type": @"assign",
                 @"ui": @"CGFloat"
                 }, @{
                 @"key": @"Frame",
                 @"type": @"assign",
                 @"ui": @"CGRect"
                 }, @{
                 @"key": @"Point",
                 @"type": @"assign",
                 @"ui": @"CGPoint"
                 }, @{
                 @"key": @"Count",
                 @"type": @"assign",
                 @"ui": @"NSInteger"
                 }, @{
                 @"key": @"int",
                 @"type": @"assign",
                 @"ui": @"NSInteger"
                 }, @{
                 @"key": @"bool",
                 @"type": @"assign",
                 @"ui": @"BOOL"
                 },
             @{ @"key": @"Array",
                @"type": @"<# type #>",
                @"ui": @"NSArray" },
             @{ @"key": @"AutoreleasePool",
                @"type": @"<# type #>",
                @"ui": @"NSAutoreleasePool" },
             @{ @"key": @"Bundle",
                @"type": @"<# type #>",
                @"ui": @"NSBundle" },
             @{ @"key": @"ByteOrder",
                @"type": @"<# type #>",
                @"ui": @"NSByteOrder" },
             @{ @"key": @"Calendar",
                @"type": @"<# type #>",
                @"ui": @"NSCalendar" },
             @{ @"key": @"CharacterSet",
                @"type": @"<# type #>",
                @"ui": @"NSCharacterSet" },
             @{ @"key": @"Coder",
                @"type": @"<# type #>",
                @"ui": @"NSCoder" },
             @{ @"key": @"Data",
                @"type": @"<# type #>",
                @"ui": @"NSData" },
             @{ @"key": @"Date",
                @"type": @"<# type #>",
                @"ui": @"NSDate" },
             @{ @"key": @"DateInterval",
                @"type": @"<# type #>",
                @"ui": @"NSDateInterval" },
             @{ @"key": @"DateFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSDateFormatter" },
             @{ @"key": @"DateIntervalFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSDateIntervalFormatter" },
             @{ @"key": @"ISO8601DateFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSISO8601DateFormatter" },
             @{ @"key": @"MassFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSMassFormatter" },
             @{ @"key": @"LengthFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSLengthFormatter" },
             @{ @"key": @"EnergyFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSEnergyFormatter" },
             @{ @"key": @"Measurement",
                @"type": @"<# type #>",
                @"ui": @"NSMeasurement" },
             @{ @"key": @"MeasurementFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSMeasurementFormatter" },
             @{ @"key": @"PersonNameComponents",
                @"type": @"<# type #>",
                @"ui": @"NSPersonNameComponents" },
             @{ @"key": @"PersonNameComponentsFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSPersonNameComponentsFormatter" },
             @{ @"key": @"Decimal",
                @"type": @"<# type #>",
                @"ui": @"NSDecimal" },
             @{ @"key": @"DecimalNumber",
                @"type": @"<# type #>",
                @"ui": @"NSDecimalNumber" },
             @{ @"key": @"Dictionary",
                @"type": @"<# type #>",
                @"ui": @"NSDictionary" },
             @{ @"key": @"Enumerator",
                @"type": @"<# type #>",
                @"ui": @"NSEnumerator" },
             @{ @"key": @"Error",
                @"type": @"<# type #>",
                @"ui": @"NSError" },
             @{ @"key": @"Exception",
                @"type": @"<# type #>",
                @"ui": @"NSException" },
             @{ @"key": @"FileHandle",
                @"type": @"<# type #>",
                @"ui": @"NSFileHandle" },
             @{ @"key": @"FileManager",
                @"type": @"<# type #>",
                @"ui": @"NSFileManager" },
             @{ @"key": @"Formatter",
                @"type": @"<# type #>",
                @"ui": @"NSFormatter" },
             @{ @"key": @"HashTable",
                @"type": @"<# type #>",
                @"ui": @"NSHashTable" },
             @{ @"key": @"HTTPCookie",
                @"type": @"<# type #>",
                @"ui": @"NSHTTPCookie" },
             @{ @"key": @"HTTPCookieStorage",
                @"type": @"<# type #>",
                @"ui": @"NSHTTPCookieStorage" },
             @{ @"key": @"IndexPath",
                @"type": @"<# type #>",
                @"ui": @"NSIndexPath" },
             @{ @"key": @"IndexSet",
                @"type": @"<# type #>",
                @"ui": @"NSIndexSet" },
             @{ @"key": @"Invocation",
                @"type": @"<# type #>",
                @"ui": @"NSInvocation" },
             @{ @"key": @"JSONSerialization",
                @"type": @"<# type #>",
                @"ui": @"NSJSONSerialization" },
             @{ @"key": @"KeyValueCoding",
                @"type": @"<# type #>",
                @"ui": @"NSKeyValueCoding" },
             @{ @"key": @"KeyValueObserving",
                @"type": @"<# type #>",
                @"ui": @"NSKeyValueObserving" },
             @{ @"key": @"KeyedArchiver",
                @"type": @"<# type #>",
                @"ui": @"NSKeyedArchiver" },
             @{ @"key": @"Locale",
                @"type": @"<# type #>",
                @"ui": @"NSLocale" },
             @{ @"key": @"Lock",
                @"type": @"<# type #>",
                @"ui": @"NSLock" },
             @{ @"key": @"MapTable",
                @"type": @"<# type #>",
                @"ui": @"NSMapTable" },
             @{ @"key": @"MethodSignature",
                @"type": @"<# type #>",
                @"ui": @"NSMethodSignature" },
             @{ @"key": @"Notification",
                @"type": @"<# type #>",
                @"ui": @"NSNotification" },
             @{ @"key": @"NotificationQueue",
                @"type": @"<# type #>",
                @"ui": @"NSNotificationQueue" },
             @{ @"key": @"Null",
                @"type": @"<# type #>",
                @"ui": @"NSNull" },
             @{ @"key": @"NumberFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSNumberFormatter" },
             @{ @"key": @"Object",
                @"type": @"<# type #>",
                @"ui": @"NSObject" },
             @{ @"key": @"Operation",
                @"type": @"<# type #>",
                @"ui": @"NSOperation" },
             @{ @"key": @"OrderedSet",
                @"type": @"<# type #>",
                @"ui": @"NSOrderedSet" },
             @{ @"key": @"Orthography",
                @"type": @"<# type #>",
                @"ui": @"NSOrthography" },
             @{ @"key": @"PathUtilities",
                @"type": @"<# type #>",
                @"ui": @"NSPathUtilities" },
             @{ @"key": @"PointerArray",
                @"type": @"<# type #>",
                @"ui": @"NSPointerArray" },
             @{ @"key": @"PointerFunctions",
                @"type": @"<# type #>",
                @"ui": @"NSPointerFunctions" },
             @{ @"key": @"Port",
                @"type": @"<# type #>",
                @"ui": @"NSPort" },
             @{ @"key": @"ProcessInfo",
                @"type": @"<# type #>",
                @"ui": @"NSProcessInfo" },
             @{ @"key": @"PropertyList",
                @"type": @"<# type #>",
                @"ui": @"NSPropertyList" },
             @{ @"key": @"Proxy",
                @"type": @"<# type #>",
                @"ui": @"NSProxy" },
             @{ @"key": @"Range",
                @"type": @"<# type #>",
                @"ui": @"NSRange" },
             @{ @"key": @"RegularExpression",
                @"type": @"<# type #>",
                @"ui": @"NSRegularExpression" },
             @{ @"key": @"RunLoop",
                @"type": @"<# type #>",
                @"ui": @"NSRunLoop" },
             @{ @"key": @"Scanner",
                @"type": @"<# type #>",
                @"ui": @"NSScanner" },
             @{ @"key": @"Set",
                @"type": @"<# type #>",
                @"ui": @"NSSet" },
             @{ @"key": @"SortDescriptor",
                @"type": @"<# type #>",
                @"ui": @"NSSortDescriptor" },
             @{ @"key": @"Stream",
                @"type": @"<# type #>",
                @"ui": @"NSStream" },
             @{ @"key": @"String",
                @"type": @"<# type #>",
                @"ui": @"NSString" },
             @{ @"key": @"TextCheckingResult",
                @"type": @"<# type #>",
                @"ui": @"NSTextCheckingResult" },
             @{ @"key": @"Thread",
                @"type": @"<# type #>",
                @"ui": @"NSThread" },
             @{ @"key": @"TimeZone",
                @"type": @"<# type #>",
                @"ui": @"NSTimeZone" },
             @{ @"key": @"Timer",
                @"type": @"<# type #>",
                @"ui": @"NSTimer" },
             @{ @"key": @"Unit",
                @"type": @"<# type #>",
                @"ui": @"NSUnit" },
             @{ @"key": @"URL",
                @"type": @"<# type #>",
                @"ui": @"NSURL" },
             @{ @"key": @"URLAuthenticationChallenge",
                @"type": @"<# type #>",
                @"ui": @"NSURLAuthenticationChallenge" },
             @{ @"key": @"URLCache",
                @"type": @"<# type #>",
                @"ui": @"NSURLCache" },
             @{ @"key": @"URLConnection",
                @"type": @"<# type #>",
                @"ui": @"NSURLConnection" },
             @{ @"key": @"URLCredential",
                @"type": @"<# type #>",
                @"ui": @"NSURLCredential" },
             @{ @"key": @"URLCredentialStorage",
                @"type": @"<# type #>",
                @"ui": @"NSURLCredentialStorage" },
             @{ @"key": @"URLError",
                @"type": @"<# type #>",
                @"ui": @"NSURLError" },
             @{ @"key": @"URLProtectionSpace",
                @"type": @"<# type #>",
                @"ui": @"NSURLProtectionSpace" },
             @{ @"key": @"URLProtocol",
                @"type": @"<# type #>",
                @"ui": @"NSURLProtocol" },
             @{ @"key": @"URLRequest",
                @"type": @"<# type #>",
                @"ui": @"NSURLRequest" },
             @{ @"key": @"URLResponse",
                @"type": @"<# type #>",
                @"ui": @"NSURLResponse" },
             @{ @"key": @"UserDefaults",
                @"type": @"<# type #>",
                @"ui": @"NSUserDefaults" },
             @{ @"key": @"Value",
                @"type": @"<# type #>",
                @"ui": @"NSValue" },
             @{ @"key": @"ValueTransformer",
                @"type": @"<# type #>",
                @"ui": @"NSValueTransformer" },
             @{ @"key": @"XMLParser",
                @"type": @"<# type #>",
                @"ui": @"NSXMLParser" },
             @{ @"key": @"XPCConnection",
                @"type": @"<# type #>",
                @"ui": @"NSXPCConnection" },
             @{ @"key": @"Zone",
                @"type": @"<# type #>",
                @"ui": @"NSZone" },
             @{ @"key": @"undationErrors",
                @"type": @"<# type #>",
                @"ui": @"NSundationErrors" },
             @{ @"key": @"AttributedString",
                @"type": @"<# type #>",
                @"ui": @"NSAttributedString" },
             @{ @"key": @"ByteCountFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSByteCountFormatter" },
             @{ @"key": @"Cache",
                @"type": @"<# type #>",
                @"ui": @"NSCache" },
             @{ @"key": @"ComparisonPredicate",
                @"type": @"<# type #>",
                @"ui": @"NSComparisonPredicate" },
             @{ @"key": @"CompoundPredicate",
                @"type": @"<# type #>",
                @"ui": @"NSCompoundPredicate" },
             @{ @"key": @"DateComponentsFormatter",
                @"type": @"<# type #>",
                @"ui": @"NSDateComponentsFormatter" },
             @{ @"key": @"Expression",
                @"type": @"<# type #>",
                @"ui": @"NSExpression" },
             @{ @"key": @"ExtensionContext",
                @"type": @"<# type #>",
                @"ui": @"NSExtensionContext" },
             @{ @"key": @"ExtensionItem",
                @"type": @"<# type #>",
                @"ui": @"NSExtensionItem" },
             @{ @"key": @"ExtensionRequestHandling",
                @"type": @"<# type #>",
                @"ui": @"NSExtensionRequestHandling" },
             @{ @"key": @"FileCoordinator",
                @"type": @"<# type #>",
                @"ui": @"NSFileCoordinator" },
             @{ @"key": @"FilePresenter",
                @"type": @"<# type #>",
                @"ui": @"NSFilePresenter" },
             @{ @"key": @"FileVersion",
                @"type": @"<# type #>",
                @"ui": @"NSFileVersion" },
             @{ @"key": @"FileWrapper",
                @"type": @"<# type #>",
                @"ui": @"NSFileWrapper" },
             @{ @"key": @"ItemProvider",
                @"type": @"<# type #>",
                @"ui": @"NSItemProvider" },
             @{ @"key": @"LinguisticTagger",
                @"type": @"<# type #>",
                @"ui": @"NSLinguisticTagger" },
             @{ @"key": @"Metadata",
                @"type": @"<# type #>",
                @"ui": @"NSMetadata" },
             @{ @"key": @"MetadataAttributes",
                @"type": @"<# type #>",
                @"ui": @"NSMetadataAttributes" },
             @{ @"key": @"NetServices",
                @"type": @"<# type #>",
                @"ui": @"NSNetServices" },
             @{ @"key": @"Predicate",
                @"type": @"<# type #>",
                @"ui": @"NSPredicate" },
             @{ @"key": @"Progress",
                @"type": @"<# type #>",
                @"ui": @"NSProgress" },
             @{ @"key": @"UbiquitousKeyValueStore",
                @"type": @"<# type #>",
                @"ui": @"NSUbiquitousKeyValueStore" },
             @{ @"key": @"UndoManager",
                @"type": @"<# type #>",
                @"ui": @"NSUndoManager" },
             @{ @"key": @"URLSession",
                @"type": @"<# type #>",
                @"ui": @"NSURLSession" },
             @{ @"key": @"UserActivity",
                @"type": @"<# type #>",
                @"ui": @"NSUserActivity" },
             @{ @"key": @"UUID",
                @"type": @"<# type #>",
                @"ui": @"NSUUID" },
             @{ @"key": @"Archiver",
                @"type": @"<# type #>",
                @"ui": @"NSArchiver" },
             @{ @"key": @"BackgroundActivityScheduler",
                @"type": @"<# type #>",
                @"ui": @"NSBackgroundActivityScheduler" },
             @{ @"key": @"CalendarDate",
                @"type": @"<# type #>",
                @"ui": @"NSCalendarDate" },
             @{ @"key": @"Connection",
                @"type": @"<# type #>",
                @"ui": @"NSConnection" },
             @{ @"key": @"DistantObject",
                @"type": @"<# type #>",
                @"ui": @"NSDistantObject" },
             @{ @"key": @"DistributedNotificationCenter",
                @"type": @"<# type #>",
                @"ui": @"NSDistributedNotificationCenter" },
             @{ @"key": @"Geometry",
                @"type": @"<# type #>",
                @"ui": @"NSGeometry" },
             @{ @"key": @"PortCoder",
                @"type": @"<# type #>",
                @"ui": @"NSPortCoder" },
             @{ @"key": @"PortMessage",
                @"type": @"<# type #>",
                @"ui": @"NSPortMessage" },
             @{ @"key": @"PortNameServer",
                @"type": @"<# type #>",
                @"ui": @"NSPortNameServer" },
             @{ @"key": @"ProtocolChecker",
                @"type": @"<# type #>",
                @"ui": @"NSProtocolChecker" },
             @{ @"key": @"Task",
                @"type": @"<# type #>",
                @"ui": @"NSTask" },
             @{ @"key": @"XMLDTD",
                @"type": @"<# type #>",
                @"ui": @"NSXMLDTD" },
             @{ @"key": @"XMLDTDNode",
                @"type": @"<# type #>",
                @"ui": @"NSXMLDTDNode" },
             @{ @"key": @"XMLDocument",
                @"type": @"<# type #>",
                @"ui": @"NSXMLDocument" },
             @{ @"key": @"XMLElement",
                @"type": @"<# type #>",
                @"ui": @"NSXMLElement" },
             @{ @"key": @"XMLNode",
                @"type": @"<# type #>",
                @"ui": @"NSXMLNode" },
             @{ @"key": @"XMLNodeOptions",
                @"type": @"<# type #>",
                @"ui": @"NSXMLNodeOptions" },
             @{ @"key": @"URLDownload",
                @"type": @"<# type #>",
                @"ui": @"NSURLDownload" },
             @{ @"key": @"URLHandle",
                @"type": @"<# type #>",
                @"ui": @"NSURLHandle" },
             @{ @"key": @"AffineTransform",
                @"type": @"<# type #>",
                @"ui": @"NSAffineTransform" },
             @{ @"key": @"AppleEventDescriptor",
                @"type": @"<# type #>",
                @"ui": @"NSAppleEventDescriptor" },
             @{ @"key": @"AppleEventManager",
                @"type": @"<# type #>",
                @"ui": @"NSAppleEventManager" },
             @{ @"key": @"AppleScript",
                @"type": @"<# type #>",
                @"ui": @"NSAppleScript" },
             @{ @"key": @"ClassDescription",
                @"type": @"<# type #>",
                @"ui": @"NSClassDescription" },
             @{ @"key": @"DistributedLock",
                @"type": @"<# type #>",
                @"ui": @"NSDistributedLock" },
             @{ @"key": @"GarbageCollector",
                @"type": @"<# type #>",
                @"ui": @"NSGarbageCollector" },
             @{ @"key": @"HFSFileTypes",
                @"type": @"<# type #>",
                @"ui": @"NSHFSFileTypes" },
             @{ @"key": @"Host",
                @"type": @"<# type #>",
                @"ui": @"NSHost" },
             @{ @"key": @"ObjectScripting",
                @"type": @"<# type #>",
                @"ui": @"NSObjectScripting" },
             @{ @"key": @"ScriptClassDescription",
                @"type": @"<# type #>",
                @"ui": @"NSScriptClassDescription" },
             @{ @"key": @"ScriptCoercionHandler",
                @"type": @"<# type #>",
                @"ui": @"NSScriptCoercionHandler" },
             @{ @"key": @"ScriptCommand",
                @"type": @"<# type #>",
                @"ui": @"NSScriptCommand" },
             @{ @"key": @"ScriptCommandDescription",
                @"type": @"<# type #>",
                @"ui": @"NSScriptCommandDescription" },
             @{ @"key": @"ScriptExecutionContext",
                @"type": @"<# type #>",
                @"ui": @"NSScriptExecutionContext" },
             @{ @"key": @"ScriptKeyValueCoding",
                @"type": @"<# type #>",
                @"ui": @"NSScriptKeyValueCoding" },
             @{ @"key": @"ScriptObjectSpecifiers",
                @"type": @"<# type #>",
                @"ui": @"NSScriptObjectSpecifiers" },
             @{ @"key": @"ScriptStandardSuiteCommands",
                @"type": @"<# type #>",
                @"ui": @"NSScriptStandardSuiteCommands" },
             @{ @"key": @"ScriptSuiteRegistry",
                @"type": @"<# type #>",
                @"ui": @"NSScriptSuiteRegistry" },
             @{ @"key": @"ScriptWhoseTests",
                @"type": @"<# type #>",
                @"ui": @"NSScriptWhoseTests" },
             @{ @"key": @"SpellServer",
                @"type": @"<# type #>",
                @"ui": @"NSSpellServer" },
             @{ @"key": @"UserNotification",
                @"type": @"<# type #>",
                @"ui": @"NSUserNotification" },
             @{ @"key": @"UserScriptTask",
                @"type": @"<# type #>",
                @"ui": @"NSUserScriptTask" },
             @{ @"key": @"KitDefines",
                @"type": @"strong",
                @"ui": @"UIKitDefines" },
             
             @{ @"key": @"Accelerometer",
                @"type": @"strong",
                @"ui": @"UIAccelerometer" },
             @{ @"key": @"Accelerometer",
                @"type": @"strong",
                @"ui": @"UIAccelerometer" },
             @{ @"key": @"Accessibility",
                @"type": @"strong",
                @"ui": @"UIAccessibility" },
             @{ @"key": @"AccessibilityConstants",
                @"type": @"strong",
                @"ui": @"UIAccessibilityConstants" },
             @{ @"key": @"AccessibilityContentSizeCategoryImageAdjusting",
                @"type": @"strong",
                @"ui": @"UIAccessibilityContentSizeCategoryImageAdjusting" },
             @{ @"key": @"AccessibilityContentSizeCategoryImageAdjusting",
                @"type": @"strong",
                @"ui": @"UIAccessibilityContentSizeCategoryImageAdjusting" },
             @{ @"key": @"ActivityIndicatorView",
                @"type": @"strong",
                @"ui": @"UIActivityIndicatorView" },
             @{ @"key": @"ActivityIndicatorView",
                @"type": @"strong",
                @"ui": @"UIActivityIndicatorView" },
             @{ @"key": @"Activity",
                @"type": @"strong",
                @"ui": @"UIActivity" },
             @{ @"key": @"ActivityItemProvider",
                @"type": @"strong",
                @"ui": @"UIActivityItemProvider" },
             @{ @"key": @"ActivityViewController",
                @"type": @"strong",
                @"ui": @"UIActivityViewController" },
             @{ @"key": @"ActionSheet",
                @"type": @"strong",
                @"ui": @"UIActionSheet" },
             @{ @"key": @"AlertController",
                @"type": @"strong",
                @"ui": @"UIAlertController" },
             @{ @"key": @"AlertView",
                @"type": @"strong",
                @"ui": @"UIAlertView" },
             @{ @"key": @"Appearance",
                @"type": @"strong",
                @"ui": @"UIAppearance" },
             @{ @"key": @"Application",
                @"type": @"strong",
                @"ui": @"UIApplication" },
             @{ @"key": @"BarButtonItem",
                @"type": @"strong",
                @"ui": @"UIBarButtonItem" },
             @{ @"key": @"BarButtonItemGroup",
                @"type": @"strong",
                @"ui": @"UIBarButtonItemGroup" },
             @{ @"key": @"BarItem",
                @"type": @"strong",
                @"ui": @"UIBarItem" },
             @{ @"key": @"BezierPath",
                @"type": @"strong",
                @"ui": @"UIBezierPath" },
             @{ @"key": @"Button",
                @"type": @"strong",
                @"ui": @"UIButton" },
             @{ @"key": @"Button",
                @"type": @"strong",
                @"ui": @"UIButton" },
             @{ @"key": @"CollectionView",
                @"type": @"strong",
                @"ui": @"UICollectionView" },
             @{ @"key": @"CollectionViewCell",
                @"type": @"strong",
                @"ui": @"UICollectionViewCell" },
             @{ @"key": @"CollectionViewController",
                @"type": @"strong",
                @"ui": @"UICollectionViewController" },
             @{ @"key": @"CollectionViewFlowLayout",
                @"type": @"strong",
                @"ui": @"UICollectionViewFlowLayout" },
             @{ @"key": @"CollectionViewLayout",
                @"type": @"strong",
                @"ui": @"UICollectionViewLayout" },
             @{ @"key": @"CollectionViewTransitionLayout",
                @"type": @"strong",
                @"ui": @"UICollectionViewTransitionLayout" },
             @{ @"key": @"Color",
                @"type": @"strong",
                @"ui": @"UIColor" },
             @{ @"key": @"ContentSizeCategoryAdjusting",
                @"type": @"strong",
                @"ui": @"UIContentSizeCategoryAdjusting" },
             @{ @"key": @"ContentSizeCategoryAdjusting",
                @"type": @"strong",
                @"ui": @"UIContentSizeCategoryAdjusting" },
             @{ @"key": @"ContentSizeCategory",
                @"type": @"strong",
                @"ui": @"UIContentSizeCategory" },
             @{ @"key": @"Control",
                @"type": @"strong",
                @"ui": @"UIControl" },
             @{ @"key": @"DataDetectors",
                @"type": @"strong",
                @"ui": @"UIDataDetectors" },
             @{ @"key": @"DatePicker",
                @"type": @"strong",
                @"ui": @"UIDatePicker" },
             @{ @"key": @"Device",
                @"type": @"strong",
                @"ui": @"UIDevice" },
             @{ @"key": @"Document",
                @"type": @"strong",
                @"ui": @"UIDocument" },
             @{ @"key": @"DocumentInteractionController",
                @"type": @"strong",
                @"ui": @"UIDocumentInteractionController" },
             @{ @"key": @"DocumentPickerViewController",
                @"type": @"strong",
                @"ui": @"UIDocumentPickerViewController" },
             @{ @"key": @"DocumentMenuViewController",
                @"type": @"strong",
                @"ui": @"UIDocumentMenuViewController" },
             @{ @"key": @"DocumentPickerExtensionViewController",
                @"type": @"strong",
                @"ui": @"UIDocumentPickerExtensionViewController" },
             @{ @"key": @"CloudSharingController",
                @"type": @"strong",
                @"ui": @"UICloudSharingController" },
             @{ @"key": @"FileProviderExtension",
                @"type": @"strong",
                @"ui": @"NSFileProviderExtension" },
             @{ @"key": @"VisualEffect",
                @"type": @"strong",
                @"ui": @"UIVisualEffect" },
             @{ @"key": @"BlurEffect",
                @"type": @"strong",
                @"ui": @"UIBlurEffect" },
             @{ @"key": @"VibrancyEffect",
                @"type": @"strong",
                @"ui": @"UIVibrancyEffect" },
             @{ @"key": @"VisualEffectView",
                @"type": @"strong",
                @"ui": @"UIVisualEffectView" },
             @{ @"key": @"Event",
                @"type": @"strong",
                @"ui": @"UIEvent" },
             @{ @"key": @"Font",
                @"type": @"strong",
                @"ui": @"UIFont" },
             @{ @"key": @"FontDescriptor",
                @"type": @"strong",
                @"ui": @"UIFontDescriptor" },
             @{ @"key": @"FontMetrics",
                @"type": @"strong",
                @"ui": @"UIFontMetrics" },
             @{ @"key": @"Geometry",
                @"type": @"strong",
                @"ui": @"UIGeometry" },
             @{ @"key": @"GestureRecognizer",
                @"type": @"strong",
                @"ui": @"UIGestureRecognizer" },
             @{ @"key": @"GestureRecognizer",
                @"type": @"strong",
                @"ui": @"UIGestureRecognizer" },
             @{ @"key": @"Graphics",
                @"type": @"strong",
                @"ui": @"UIGraphics" },
             @{ @"key": @"Image",
                @"type": @"strong",
                @"ui": @"UIImage" },
             @{ @"key": @"GraphicsRenderer",
                @"type": @"strong",
                @"ui": @"UIGraphicsRenderer" },
             @{ @"key": @"GraphicsRenderer",
                @"type": @"strong",
                @"ui": @"UIGraphicsRenderer" },
             @{ @"key": @"GraphicsImageRenderer",
                @"type": @"strong",
                @"ui": @"UIGraphicsImageRenderer" },
             @{ @"key": @"GraphicsPDFRenderer",
                @"type": @"strong",
                @"ui": @"UIGraphicsPDFRenderer" },
             @{ @"key": @"ImageAsset",
                @"type": @"strong",
                @"ui": @"UIImageAsset" },
             @{ @"key": @"ImageAsset",
                @"type": @"strong",
                @"ui": @"UIImageAsset" },
             @{ @"key": @"DataAsset",
                @"type": @"strong",
                @"ui": @"NSDataAsset" },
             @{ @"key": @"ImagePickerController",
                @"type": @"strong",
                @"ui": @"UIImagePickerController" },
             @{ @"key": @"ImageView",
                @"type": @"strong",
                @"ui": @"UIImageView" },
             @{ @"key": @"InputView",
                @"type": @"strong",
                @"ui": @"UIInputView" },
             @{ @"key": @"InputViewController",
                @"type": @"strong",
                @"ui": @"UIInputViewController" },
             @{ @"key": @"Interface",
                @"type": @"strong",
                @"ui": @"UIInterface" },
             @{ @"key": @"Label",
                @"type": @"strong",
                @"ui": @"UILabel" },
             @{ @"key": @"Lexicon",
                @"type": @"strong",
                @"ui": @"UILexicon" },
             @{ @"key": @"LocalNotification",
                @"type": @"strong",
                @"ui": @"UILocalNotification" },
             @{ @"key": @"UserNotificationSettings",
                @"type": @"strong",
                @"ui": @"UIUserNotificationSettings" },
             @{ @"key": @"ApplicationShortcutItem",
                @"type": @"strong",
                @"ui": @"UIApplicationShortcutItem" },
             @{ @"key": @"UserNotificationSettings",
                @"type": @"strong",
                @"ui": @"UIUserNotificationSettings" },
             @{ @"key": @"Focus",
                @"type": @"strong",
                @"ui": @"UIFocus" },
             @{ @"key": @"FocusSystem",
                @"type": @"strong",
                @"ui": @"UIFocusSystem" },
             @{ @"key": @"FocusGuide",
                @"type": @"strong",
                @"ui": @"UIFocusGuide" },
             @{ @"key": @"FocusAnimationCoordinator",
                @"type": @"strong",
                @"ui": @"UIFocusAnimationCoordinator" },
             @{ @"key": @"FocusDebugger",
                @"type": @"strong",
                @"ui": @"UIFocusDebugger" },
             @{ @"key": @"FocusMovementHint",
                @"type": @"strong",
                @"ui": @"UIFocusMovementHint" },
             @{ @"key": @"LocalizedIndexedCollation",
                @"type": @"strong",
                @"ui": @"UILocalizedIndexedCollation" },
             @{ @"key": @"LongPressGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UILongPressGestureRecognizer" },
             @{ @"key": @"ManagedDocument",
                @"type": @"strong",
                @"ui": @"UIManagedDocument" },
             @{ @"key": @"MenuController",
                @"type": @"strong",
                @"ui": @"UIMenuController" },
             @{ @"key": @"MotionEffect",
                @"type": @"strong",
                @"ui": @"UIMotionEffect" },
             @{ @"key": @"NavigationBar",
                @"type": @"strong",
                @"ui": @"UINavigationBar" },
             @{ @"key": @"NavigationController",
                @"type": @"strong",
                @"ui": @"UINavigationController" },
             @{ @"key": @"Nib",
                @"type": @"strong",
                @"ui": @"UINib" },
             @{ @"key": @"NibDeclarations",
                @"type": @"strong",
                @"ui": @"UINibDeclarations" },
             @{ @"key": @"NibLoading",
                @"type": @"strong",
                @"ui": @"UINibLoading" },
             @{ @"key": @"PageControl",
                @"type": @"strong",
                @"ui": @"UIPageControl" },
             @{ @"key": @"PageViewController",
                @"type": @"strong",
                @"ui": @"UIPageViewController" },
             @{ @"key": @"PanGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UIPanGestureRecognizer" },
             @{ @"key": @"Pasteboard",
                @"type": @"strong",
                @"ui": @"UIPasteboard" },
             @{ @"key": @"PasteConfiguration",
                @"type": @"strong",
                @"ui": @"UIPasteConfiguration" },
             @{ @"key": @"PasteConfigurationSupporting",
                @"type": @"strong",
                @"ui": @"UIPasteConfigurationSupporting" },
             @{ @"key": @"PickerView",
                @"type": @"strong",
                @"ui": @"UIPickerView" },
             @{ @"key": @"PinchGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UIPinchGestureRecognizer" },
             @{ @"key": @"PopoverController",
                @"type": @"strong",
                @"ui": @"UIPopoverController" },
             @{ @"key": @"PopoverBackgroundView",
                @"type": @"strong",
                @"ui": @"UIPopoverBackgroundView" },
             @{ @"key": @"Press",
                @"type": @"strong",
                @"ui": @"UIPress" },
             @{ @"key": @"PressesEvent",
                @"type": @"strong",
                @"ui": @"UIPressesEvent" },
             @{ @"key": @"Printer",
                @"type": @"strong",
                @"ui": @"UIPrinter" },
             @{ @"key": @"PrinterPickerController",
                @"type": @"strong",
                @"ui": @"UIPrinterPickerController" },
             @{ @"key": @"PrintError",
                @"type": @"strong",
                @"ui": @"UIPrintError" },
             @{ @"key": @"PrintFormatter",
                @"type": @"strong",
                @"ui": @"UIPrintFormatter" },
             @{ @"key": @"PrintInfo",
                @"type": @"strong",
                @"ui": @"UIPrintInfo" },
             @{ @"key": @"PrintInteractionController",
                @"type": @"strong",
                @"ui": @"UIPrintInteractionController" },
             @{ @"key": @"PrintPageRenderer",
                @"type": @"strong",
                @"ui": @"UIPrintPageRenderer" },
             @{ @"key": @"PrintPaper",
                @"type": @"strong",
                @"ui": @"UIPrintPaper" },
             @{ @"key": @"ProgressView",
                @"type": @"strong",
                @"ui": @"UIProgressView" },
             @{ @"key": @"ReferenceLibraryViewController",
                @"type": @"strong",
                @"ui": @"UIReferenceLibraryViewController" },
             @{ @"key": @"RefreshControl",
                @"type": @"strong",
                @"ui": @"UIRefreshControl" },
             @{ @"key": @"Responder",
                @"type": @"strong",
                @"ui": @"UIResponder" },
             @{ @"key": @"RotationGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UIRotationGestureRecognizer" },
             @{ @"key": @"Screen",
                @"type": @"strong",
                @"ui": @"UIScreen" },
             @{ @"key": @"ScreenEdgePanGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UIScreenEdgePanGestureRecognizer" },
             @{ @"key": @"ScreenMode",
                @"type": @"strong",
                @"ui": @"UIScreenMode" },
             @{ @"key": @"ScrollView",
                @"type": @"strong",
                @"ui": @"UIScrollView" },
             @{ @"key": @"SearchBar",
                @"type": @"strong",
                @"ui": @"UISearchBar" },
             @{ @"key": @"SearchContainerViewController",
                @"type": @"strong",
                @"ui": @"UISearchContainerViewController" },
             @{ @"key": @"SearchController",
                @"type": @"strong",
                @"ui": @"UISearchController" },
             @{ @"key": @"SearchDisplayController",
                @"type": @"strong",
                @"ui": @"UISearchDisplayController" },
             @{ @"key": @"SegmentedControl",
                @"type": @"strong",
                @"ui": @"UISegmentedControl" },
             @{ @"key": @"Slider",
                @"type": @"strong",
                @"ui": @"UISlider" },
             @{ @"key": @"SplitViewController",
                @"type": @"strong",
                @"ui": @"UISplitViewController" },
             @{ @"key": @"Stepper",
                @"type": @"strong",
                @"ui": @"UIStepper" },
             @{ @"key": @"Storyboard",
                @"type": @"strong",
                @"ui": @"UIStoryboard" },
             @{ @"key": @"StoryboardPopoverSegue",
                @"type": @"strong",
                @"ui": @"UIStoryboardPopoverSegue" },
             @{ @"key": @"StoryboardSegue",
                @"type": @"strong",
                @"ui": @"UIStoryboardSegue" },
             @{ @"key": @"StringDrawing",
                @"type": @"strong",
                @"ui": @"UIStringDrawing" },
             @{ @"key": @"SwipeGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UISwipeGestureRecognizer" },
             @{ @"key": @"Switch",
                @"type": @"strong",
                @"ui": @"UISwitch" },
             @{ @"key": @"TabBar",
                @"type": @"strong",
                @"ui": @"UITabBar" },
             @{ @"key": @"TabBarController",
                @"type": @"strong",
                @"ui": @"UITabBarController" },
             @{ @"key": @"TabBarItem",
                @"type": @"strong",
                @"ui": @"UITabBarItem" },
             @{ @"key": @"TableView",
                @"type": @"strong",
                @"ui": @"UITableView" },
             @{ @"key": @"TableViewHeaderFooterView",
                @"type": @"strong",
                @"ui": @"UITableViewHeaderFooterView" },
             @{ @"key": @"TableViewCell",
                @"type": @"strong",
                @"ui": @"UITableViewCell" },
             @{ @"key": @"TableViewController",
                @"type": @"strong",
                @"ui": @"UITableViewController" },
             @{ @"key": @"TapGestureRecognizer",
                @"type": @"strong",
                @"ui": @"UITapGestureRecognizer" },
             @{ @"key": @"TextChecker",
                @"type": @"strong",
                @"ui": @"UITextChecker" },
             @{ @"key": @"TextField",
                @"type": @"strong",
                @"ui": @"UITextField" },
             @{ @"key": @"TextInput",
                @"type": @"strong",
                @"ui": @"UITextInput" },
             @{ @"key": @"TextInputTraits",
                @"type": @"strong",
                @"ui": @"UITextInputTraits" },
             @{ @"key": @"TextView",
                @"type": @"strong",
                @"ui": @"UITextView" },
             @{ @"key": @"Toolbar",
                @"type": @"strong",
                @"ui": @"UIToolbar" },
             @{ @"key": @"Touch",
                @"type": @"strong",
                @"ui": @"UITouch" },
             @{ @"key": @"TraitCollection",
                @"type": @"strong",
                @"ui": @"UITraitCollection" },
             @{ @"key": @"UserActivity",
                @"type": @"strong",
                @"ui": @"UIUserActivity" },
             @{ @"key": @"VideoEditorController",
                @"type": @"strong",
                @"ui": @"UIVideoEditorController" },
             @{ @"key": @"View",
                @"type": @"strong",
                @"ui": @"UIView" },
             @{ @"key": @"ViewController",
                @"type": @"strong",
                @"ui": @"UIViewController" },
             @{ @"key": @"WebView",
                @"type": @"strong",
                @"ui": @"UIWebView" },
             @{ @"key": @"Window",
                @"type": @"strong",
                @"ui": @"UIWindow" },
             @{ @"key": @"DragInteraction",
                @"type": @"strong",
                @"ui": @"UIDragInteraction" },
             @{ @"key": @"DragItem",
                @"type": @"strong",
                @"ui": @"UIDragItem" },
             @{ @"key": @"DragPreview",
                @"type": @"strong",
                @"ui": @"UIDragPreview" },
             @{ @"key": @"DragPreviewParameters",
                @"type": @"strong",
                @"ui": @"UIDragPreviewParameters" },
             @{ @"key": @"DragSession",
                @"type": @"strong",
                @"ui": @"UIDragSession" },
             @{ @"key": @"DropInteraction",
                @"type": @"strong",
                @"ui": @"UIDropInteraction" },
             @{ @"key": @"Interaction",
                @"type": @"strong",
                @"ui": @"UIInteraction" },
             @{ @"key": @"TargetedDragPreview",
                @"type": @"strong",
                @"ui": @"UITargetedDragPreview" },
             @{ @"key": @"SpringLoadedInteraction",
                @"type": @"strong",
                @"ui": @"UISpringLoadedInteraction" },
             @{ @"key": @"SpringLoadedInteractionSupporting",
                @"type": @"strong",
                @"ui": @"UISpringLoadedInteractionSupporting" },
             @{ @"key": @"AttributedString",
                @"type": @"strong",
                @"ui": @"NSAttributedString" },
             @{ @"key": @"ItemProvider+UIKitAdditions",
                @"type": @"strong",
                @"ui": @"NSItemProvider+UIKitAdditions" },
             @{ @"key": @"ItemProvider+UIKitAdditions",
                @"type": @"strong",
                @"ui": @"NSItemProvider+UIKitAdditions" },
             @{ @"key": @"LayoutConstraint",
                @"type": @"strong",
                @"ui": @"NSLayoutConstraint" },
             @{ @"key": @"LayoutConstraint",
                @"type": @"strong",
                @"ui": @"NSLayoutConstraint" },
             @{ @"key": @"LayoutAnchor",
                @"type": @"strong",
                @"ui": @"NSLayoutAnchor" },
             @{ @"key": @"LayoutGuide",
                @"type": @"strong",
                @"ui": @"UILayoutGuide" },
             @{ @"key": @"StackView",
                @"type": @"strong",
                @"ui": @"UIStackView" },
             @{ @"key": @"LayoutManager",
                @"type": @"strong",
                @"ui": @"NSLayoutManager" },
             @{ @"key": @"ParagraphStyle",
                @"type": @"strong",
                @"ui": @"NSParagraphStyle" },
             @{ @"key": @"Shadow",
                @"type": @"strong",
                @"ui": @"NSShadow" },
             @{ @"key": @"Shadow",
                @"type": @"strong",
                @"ui": @"NSShadow" },
             @{ @"key": @"StringDrawing",
                @"type": @"strong",
                @"ui": @"NSStringDrawing" },
             @{ @"key": @"Text",
                @"type": @"strong",
                @"ui": @"NSText" },
             @{ @"key": @"TextAttachment",
                @"type": @"strong",
                @"ui": @"NSTextAttachment" },
             @{ @"key": @"TextAttachment",
                @"type": @"strong",
                @"ui": @"NSTextAttachment" },
             @{ @"key": @"TextContainer",
                @"type": @"strong",
                @"ui": @"NSTextContainer" },
             @{ @"key": @"TextStorage",
                @"type": @"strong",
                @"ui": @"NSTextStorage" },
             @{ @"key": @"StateRestoration",
                @"type": @"strong",
                @"ui": @"UIStateRestoration" },
             @{ @"key": @"ViewControllerTransitioning",
                @"type": @"strong",
                @"ui": @"UIViewControllerTransitioning" },
             @{ @"key": @"ViewControllerTransitionCoordinator",
                @"type": @"strong",
                @"ui": @"UIViewControllerTransitionCoordinator" },
             @{ @"key": @"PresentationController",
                @"type": @"strong",
                @"ui": @"UIPresentationController" },
             @{ @"key": @"PreviewInteraction",
                @"type": @"strong",
                @"ui": @"UIPreviewInteraction" },
             @{ @"key": @"PopoverPresentationController",
                @"type": @"strong",
                @"ui": @"UIPopoverPresentationController" },
             @{ @"key": @"DynamicAnimator",
                @"type": @"strong",
                @"ui": @"UIDynamicAnimator" },
             @{ @"key": @"DynamicBehavior",
                @"type": @"strong",
                @"ui": @"UIDynamicBehavior" },
             @{ @"key": @"PushBehavior",
                @"type": @"strong",
                @"ui": @"UIPushBehavior" },
             @{ @"key": @"SnapBehavior",
                @"type": @"strong",
                @"ui": @"UISnapBehavior" },
             @{ @"key": @"DynamicItemBehavior",
                @"type": @"strong",
                @"ui": @"UIDynamicItemBehavior" },
             @{ @"key": @"FieldBehavior",
                @"type": @"strong",
                @"ui": @"UIFieldBehavior" },
             @{ @"key": @"GravityBehavior",
                @"type": @"strong",
                @"ui": @"UIGravityBehavior" },
             @{ @"key": @"AttachmentBehavior",
                @"type": @"strong",
                @"ui": @"UIAttachmentBehavior" },
             @{ @"key": @"CollisionBehavior",
                @"type": @"strong",
                @"ui": @"UICollisionBehavior" },
             @{ @"key": @"Region",
                @"type": @"strong",
                @"ui": @"UIRegion" },
             @{ @"key": @"TextDragging",
                @"type": @"strong",
                @"ui": @"UITextDragging" },
             @{ @"key": @"TextDragging",
                @"type": @"strong",
                @"ui": @"UITextDragging" },
             @{ @"key": @"TextDropping",
                @"type": @"strong",
                @"ui": @"UITextDropping" },
             @{ @"key": @"TextDropProposal",
                @"type": @"strong",
                @"ui": @"UITextDropProposal" },
             @{ @"key": @"TextDragPreviewRenderer",
                @"type": @"strong",
                @"ui": @"UITextDragPreviewRenderer" },
             @{ @"key": @"TextDragURLPreviews",
                @"type": @"strong",
                @"ui": @"UITextDragURLPreviews" },
             @{ @"key": @"ViewPropertyAnimator",
                @"type": @"strong",
                @"ui": @"UIViewPropertyAnimator" },
             @{ @"key": @"ViewPropertyAnimator",
                @"type": @"strong",
                @"ui": @"UIViewPropertyAnimator" },
             @{ @"key": @"FeedbackGenerator",
                @"type": @"strong",
                @"ui": @"UIFeedbackGenerator" },
             @{ @"key": @"FeedbackGenerator",
                @"type": @"strong",
                @"ui": @"UIFeedbackGenerator" },
             @{ @"key": @"SelectionFeedbackGenerator",
                @"type": @"strong",
                @"ui": @"UISelectionFeedbackGenerator" },
             @{ @"key": @"ImpactFeedbackGenerator",
                @"type": @"strong",
                @"ui": @"UIImpactFeedbackGenerator" },
             @{ @"key": @"NotificationFeedbackGenerator",
                @"type": @"strong",
                @"ui": @"UINotificationFeedbackGenerator" },
             @{ @"key": @"TimingCurveProvider",
                @"type": @"strong",
                @"ui": @"UITimingCurveProvider" },
             @{ @"key": @"TimingCurveProvider",
                @"type": @"strong",
                @"ui": @"UITimingCurveProvider" },
             @{ @"key": @"IndexPath+UIKitAdditions",
                @"type": @"strong",
                @"ui": @"NSIndexPath+UIKitAdditions" },
             @{ @"key": @"IndexPath+UIKitAdditions",
                @"type": @"strong",
                @"ui": @"NSIndexPath+UIKitAdditions" },
             @{ @"key": @"PopoverSupport",
                @"type": @"strong",
                @"ui": @"UIPopoverSupport" },
             @{ @"key": @"PopoverSupport",
                @"type": @"strong",
                @"ui": @"UIPopoverSupport" },
             @{ @"key": @"TextItemInteraction",
                @"type": @"strong",
                @"ui": @"UITextItemInteraction" },
             @{ @"key": @"TextItemInteraction",
                @"type": @"strong",
                @"ui": @"UITextItemInteraction" },
             @{ @"key": @"ViewAnimating",
                @"type": @"strong",
                @"ui": @"UIViewAnimating" },
             @{ @"key": @"ViewAnimating",
                @"type": @"strong",
                @"ui": @"UIViewAnimating" },
             @{ @"key": @"SwipeActionsConfiguration",
                @"type": @"strong",
                @"ui": @"UISwipeActionsConfiguration" },
             @{ @"key": @"SwipeActionsConfiguration",
                @"type": @"strong",
                @"ui": @"UISwipeActionsConfiguration" },
             @{ @"key": @"AccessibilityZoom",
                @"type": @"strong",
                @"ui": @"UIAccessibilityZoom" },
             @{ @"key": @"AccessibilityZoom",
                @"type": @"strong",
                @"ui": @"UIAccessibilityZoom" },
             @{ @"key": @"AccessibilityCustomAction",
                @"type": @"strong",
                @"ui": @"UIAccessibilityCustomAction" },
             @{ @"key": @"AccessibilityCustomAction",
                @"type": @"strong",
                @"ui": @"UIAccessibilityCustomAction" },
             @{ @"key": @"DataSourceTranslating",
                @"type": @"strong",
                @"ui": @"UIDataSourceTranslating" },
             @{ @"key": @"DataSourceTranslating",
                @"type": @"strong",
                @"ui": @"UIDataSourceTranslating" },
             @{ @"key": @"AccessibilityElement",
                @"type": @"strong",
                @"ui": @"UIAccessibilityElement" },
             @{ @"key": @"AccessibilityElement",
                @"type": @"strong",
                @"ui": @"UIAccessibilityElement" },
             @{ @"key": @"TextPasteDelegate",
                @"type": @"strong",
                @"ui": @"UITextPasteDelegate" },
             @{ @"key": @"TextPasteDelegate",
                @"type": @"strong",
                @"ui": @"UITextPasteDelegate" },
             @{ @"key": @"TextPasteConfigurationSupporting",
                @"type": @"strong",
                @"ui": @"UITextPasteConfigurationSupporting" },
             @{ @"key": @"TextPasteConfigurationSupporting",
                @"type": @"strong",
                @"ui": @"UITextPasteConfigurationSupporting" },
             @{ @"key": @"Alert",
                @"type": @"strong",
                @"ui": @"UIAlert" },
             @{ @"key": @"Alert",
                @"type": @"strong",
                @"ui": @"UIAlert" },
             @{ @"key": @"AccessibilityLocationDescriptor",
                @"type": @"strong",
                @"ui": @"UIAccessibilityLocationDescriptor" },
             @{ @"key": @"AccessibilityLocationDescriptor",
                @"type": @"strong",
                @"ui": @"UIAccessibilityLocationDescriptor" },
             @{ @"key": @"NavigationItem",
                @"type": @"strong",
                @"ui": @"UINavigationItem" },
             @{ @"key": @"NavigationItem",
                @"type": @"strong",
                @"ui": @"UINavigationItem" },
             @{ @"key": @"AccessibilityAdditions",
                @"type": @"strong",
                @"ui": @"UIAccessibilityAdditions" },
             @{ @"key": @"AccessibilityAdditions",
                @"type": @"strong",
                @"ui": @"UIAccessibilityAdditions" },
             @{ @"key": @"TimingParameters",
                @"type": @"strong",
                @"ui": @"UITimingParameters" },
             @{ @"key": @"TimingParameters",
                @"type": @"strong",
                @"ui": @"UITimingParameters" },
             @{ @"key": @"BarCommon",
                @"type": @"strong",
                @"ui": @"UIBarCommon" },
             @{ @"key": @"BarCommon",
                @"type": @"strong",
                @"ui": @"UIBarCommon" },
             @{ @"key": @"GuidedAccessRestrictions",
                @"type": @"strong",
                @"ui": @"UIGuidedAccessRestrictions" },
             @{ @"key": @"GuidedAccessRestrictions",
                @"type": @"strong",
                @"ui": @"UIGuidedAccessRestrictions" },
             @{ @"key": @"AccessibilityCustomRotor",
                @"type": @"strong",
                @"ui": @"UIAccessibilityCustomRotor" },
             @{ @"key": @"AccessibilityCustomRotor",
                @"type": @"strong",
                @"ui": @"UIAccessibilityCustomRotor" },
             @{ @"key": @"ContextualAction",
                @"type": @"strong",
                @"ui": @"UIContextualAction" },
             @{ @"key": @"ContextualAction",
                @"type": @"strong",
                @"ui": @"UIContextualAction" },
             @{ @"key": @"AccessibilityContainer",
                @"type": @"strong",
                @"ui": @"UIAccessibilityContainer" },
             @{ @"key": @"AccessibilityContainer",
                @"type": @"strong",
                @"ui": @"UIAccessibilityContainer" },
             @{ @"key": @"AccessibilityIdentification",
                @"type": @"strong",
                @"ui": @"UIAccessibilityIdentification" },
             @{ @"key": @"AccessibilityIdentification",
                @"type": @"strong",
                @"ui": @"UIAccessibilityIdentification" },
             @{ @"key": @"GestureRecognizerSubclass",
                @"type": @"strong",
                @"ui": @"UIGestureRecognizerSubclass" },
             @{ @"key": @"GestureRecognizerSubclass",
                @"type": @"strong",
                @"ui": @"UIGestureRecognizerSubclass" },
             @{ @"key": @"GraphicsRendererSubclass",
                @"type": @"strong",
                @"ui": @"UIGraphicsRendererSubclass" },
             @{ @"key": @"GraphicsRendererSubclass",
                @"type": @"strong",
                @"ui": @"UIGraphicsRendererSubclass" },
             @{ @"key": @"FocusMovementHint",
                @"type": @"strong",
                @"ui": @"UIFocusMovementHint" },
             @{ @"key": @"FocusMovementHint",
                @"type": @"strong",
                @"ui": @"UIFocusMovementHint" },
             @{ @"key": @"PencilInteraction",
                @"type": @"strong",
                @"ui": @"UIPencilInteraction" },
             @{ @"key": @"PencilInteraction",
                @"type": @"strong",
                @"ui": @"UIPencilInteraction" }, ];
}

@end
